name: smart_box
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  google_nav_bar: ^5.0.7
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  anim_search_bar: ^2.0.3
  pretty_gauge: ^1.0.1
  image_picker: ^1.1.2
  fl_chart: ^0.71.0
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  flutter_local_notifications: ^19.1.0
  # flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^12.0.0+1
  flutter_slidable: ^4.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/img/out-of-stock.png
    - assets/img/boxes.png
    - assets/img/logo_smart_box.png
    - assets/img/apple.png
    - assets/img/facebook.png
    - assets/img/google.png
    - assets/img/location.png
    - assets/img/add-product.png
    - assets/img/logo_smart_box_splash.png
    - assets/img/smart_box_text.png
    - assets/img/splash_icon_white_bg.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/img/splash_icon_white_bg.png
  branding: assets/img/smart_box_text.png
  android: true
  ios: true

  android_12:
    color: "#ffffff"
    image: assets/img/splash_icon_white_bg.png
    branding: assets/img/smart_box_text.png
    