// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaMFkm40c7rZRXXH0g9FZ1Kg69ymjkxHg',
    appId: '1:611402151300:web:f21003e78832457fc0d9d1',
    messagingSenderId: '611402151300',
    projectId: 'smart-box-6c453',
    authDomain: 'smart-box-6c453.firebaseapp.com',
    storageBucket: 'smart-box-6c453.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPbvecJSc8dZNgYzd5lOYT6oXJGjmx6cQ',
    appId: '1:611402151300:android:8a38efcb2d901ce1c0d9d1',
    messagingSenderId: '611402151300',
    projectId: 'smart-box-6c453',
    storageBucket: 'smart-box-6c453.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD96bZOk0Ul3gK4HOl9ChM6gQXInjFuieU',
    appId: '1:611402151300:ios:21e86a48bc063ae6c0d9d1',
    messagingSenderId: '611402151300',
    projectId: 'smart-box-6c453',
    storageBucket: 'smart-box-6c453.firebasestorage.app',
    iosBundleId: 'com.example.smartBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD96bZOk0Ul3gK4HOl9ChM6gQXInjFuieU',
    appId: '1:611402151300:ios:21e86a48bc063ae6c0d9d1',
    messagingSenderId: '611402151300',
    projectId: 'smart-box-6c453',
    storageBucket: 'smart-box-6c453.firebasestorage.app',
    iosBundleId: 'com.example.smartBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaMFkm40c7rZRXXH0g9FZ1Kg69ymjkxHg',
    appId: '1:611402151300:web:4872211eb3ae73bdc0d9d1',
    messagingSenderId: '611402151300',
    projectId: 'smart-box-6c453',
    authDomain: 'smart-box-6c453.firebaseapp.com',
    storageBucket: 'smart-box-6c453.firebasestorage.app',
  );
}
