name: smart_box
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  google_nav_bar: ^5.0.7
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  anim_search_bar: ^2.0.3
  syncfusion_flutter_gauges: ^29.1.37
  # lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/logo_smart_box.png
  - assets/logo_smart_box_white.png
